version: "3.5"
services:
  notes_capture:
    build: .
    container_name: notes_capture
    restart: always
    networks:
      - db
    ports:
      - 80:80
    volumes:
      - ./code:/var/www/html
      - ./data:/data
      - ./backup:/backup
    env_file:
      - .env
  db:
    image: mysql
    container_name: notes_capture_mysql
    restart: always
    networks:
      - db
    ports:
      - 8002:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql_startup:/docker-entrypoint-initdb.d
    env_file:
      - .env
  phpmyadmin:
    image: 157239n/phpmyadmin
    container_name: notes_capture_phpmyadmin
    restart: always
    networks:
      - db
    ports:
      - 8001:80
    env_file:
      - .env
networks:
  db: